{{ if and .Values.galaxy.admin.email (and .Values.galaxy.admin.password .Values.galaxy.admin.api_key) }}
apiVersion: v1
kind: Secret
metadata:
  name: galaxy-admin-secret 
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  password: {{ b64enc .Values.galaxy.admin.password }}
  api-key: {{ b64enc .Values.galaxy.admin.api_key }}
  database_password: {{ b64enc .Values.postgresql.postgresPassword }}
{{ end }}
