# This config map contains miscellaneous container env vars.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "galaxy.fullname" . }}-container-cfgmap
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  "NONUSE": "sleeplock{{ if not .Values.condor.enabled }},condor{{ end }}"
  "GALAXY_TOOLS_PULL_POLICY": {{ .Values.image.pullPolicy }}
  {{- if .Values.postgresql.enabled }}
  "GALAXY_SEC_DB_ENGINE": "postgresql"
  "GALAXY_SEC_DB_USER": {{ .Values.postgresql.postgresUser }}
  "GALAXY_SEC_DB_HOST": {{ template "postgresql.fullname" . }}
  "GALAXY_SEC_DB_NAME": {{ .Values.postgresql.postgresDatabase }}
# "GALAXY_CONFIG_DATABASE_CONNECTION": ${GALAXY_SEC_DB_ENGINE}://${GALAXY_SEC_DB_USER}:${GALAXY_SEC_DB_PASS}@${GALAXY_SEC_DB_HOST}/${GALAXY_SEC_DB_NAME}?client_encoding=utf8
  {{- end }}
  {{- if .Values.tools.destination }}
  "TOOLS_DEST_PVC": "{{ .Values.tools.destination }}"
  "GALAXY_CONFIG_TOOL_PATH": "{{ .Values.tools.destination }}"
  {{- end }}
  {{- if .Values.k8s.supp_groups }}
  "SUPP_GROUPS": "{{ .Values.k8s.supp_groups }}"
  {{ end }}
  {{- if .Values.k8s.fs_group }}
  "FS_GROUP": "{{ .Values.k8s.fs_group }}"
  {{- end }}
  {{- if and .Values.admin.email (and .Values.admin.password .Values.admin.api_key) }}
  "GALAXY_DEFAULT_ADMIN_USER": {{ quote .Values.admin.username }}
  "GALAXY_DEFAULT_ADMIN_EMAIL": {{ quote .Values.admin.email }}
  "GALAXY_ADMIN_EMAIL": {{ quote .Values.admin.email }}
  {{- end }}
  "PYKUBE_KUBERNETES_SERVICE_HOST": "kubernetes"
  {{- if not (eq .Values.ingress.path "/") }}
  "PROXY_PREFIX": "{{ .Values.ingress.path }}"
  {{- end }}

  {{- range $key, $val := .Values.uwsgi}}
  {{- if $val }}
  UWSGI_{{ $key | upper }}: {{ quote $val }}
  {{- end }}
  {{- end }}

  {{- range $key, $val := .Values.job_conf.runners }}
  {{- if $val }}
  GALAXY_RUNNERS_{{ $key | upper }}: {{ quote $val }}
  {{- end }}
  {{- end }}

  {{- range $key, $val := .Values.job_conf.destinations }}
  {{- if $val }}
  GALAXY_DESTINATIONS_{{ $key | upper }}: {{ quote $val }}
  {{- end }}
  {{- end }}
