{{ if .Values.pv_minikube }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-pv
  labels:
     app: {{ template "name" . }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ .Values.pv.minikube.hostPath }}"
    type: DirectoryOrCreate
{{ end }}
