image:
  repository: galaxy/galaxy-k8s
  tag: 20.01
  pullPolicy: IfNotPresent

webHandlers:
  replicaCount: 1

jobHandlers:
  replicaCount: 1

persistence:
  storageClass: standard

influxdb:
  enabled: false

postgresql:
  persistence:
    storageClass: standard
