apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "galaxy.fullname" . }}-job-rules
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
data:
  {{- range $key, $entry := .Values.jobs.rules -}}
  {{- if $entry -}}
  {{- $key | nindent 2 }}: |
    {{- tpl (tpl $entry $) $ | nindent 4 -}}
  {{- end }}
  {{- end }}
