{{- range $key, $entry := .Values.extraFileMappings -}}
{{- if $entry }}
apiVersion: v1
metadata:
  # Extract the filename portion only
  name: {{ printf "%s-%s" (include "galaxy.fullname" $) (include "galaxy.getExtraFilesUniqueName" $key) }}
  labels:
    {{- include "galaxy.labels" $ | nindent 4 }}
{{- if $entry.useSecret }}
kind: Secret
type: Opaque
stringData:
{{- else }}
kind: ConfigMap
data:
{{- end }}
  {{- include "galaxy.getFilenameFromPath" $key | nindent 2 }}: |
    {{- tpl (tpl $entry.content $) $ | nindent 4 }}
---
{{- end }}
{{- end }}
apiVersion: v1
metadata:
  name: {{ include "galaxy.fullname" $ }}-probedb-py
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
kind: ConfigMap
data:
  probedb.py: |
    {{- (.Files.Get "scripts/probedb.py") | nindent 4 }}

---