apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "galaxy.fullname" . }}-nginx-conf
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes  4;

    events {
        worker_connections  1024;
    }

    http {
        default_type  application/octet-stream;
        include /etc/nginx/mime.types;
        sendfile        on;
        keepalive_timeout  65;
        index   index.html index.php index.htm;

        gzip  on;
        gzip_http_version 1.1;
        gzip_vary on;
        gzip_comp_level 6;
        gzip_proxied any;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;
        gzip_buffers 16 8k;
        proxy_read_timeout 600;
        uwsgi_buffer_size   128k;
        uwsgi_buffers   4 256k;
        uwsgi_busy_buffers_size   256k;
        uwsgi_read_timeout 600;
        uwsgi_send_timeout 600;
        client_max_body_size {{ .Values.nginx.conf.client_max_body_size }};

        server {
            listen {{ .Values.nginx.containerPort }};
            server_name galaxy;

            location {{ template "galaxy.add_trailing_slash" .Values.ingress.path }}static {
                alias {{ .Values.nginx.galaxyStaticDir }};
                expires 24h;
            }

            location {{ template "galaxy.add_trailing_slash" .Values.ingress.path }} {
                uwsgi_pass {{ template "galaxy.fullname" . }}-uwsgi:4001;
                uwsgi_param UWSGI_SCHEME $scheme;
                include uwsgi_params;
            }

            location ^~ {{ template "galaxy.add_trailing_slash" .Values.ingress.path }}admin_toolshed/static {
                uwsgi_pass {{ template "galaxy.fullname" . }}-uwsgi:4001;
                uwsgi_param UWSGI_SCHEME $scheme;
                include uwsgi_params;
            }

            location ~ ^{{ template "galaxy.add_trailing_slash" .Values.ingress.path }}api/dataset_collections/([^/]+)/download/?$ {
                proxy_buffering off;
                uwsgi_pass {{ template "galaxy.fullname" . }}-uwsgi:4001;
                uwsgi_param UWSGI_SCHEME $scheme;
                include uwsgi_params;
            }

            location {{ template "galaxy.add_trailing_slash" .Values.ingress.path }}_x_accel_redirect/ {
                internal;
                alias /;
                add_header X-Frame-Options SAMEORIGIN;
                add_header X-Content-Type-Options nosniff;
            }

{{ if .Values.tusd.enabled }}
            location {{ template "galaxy.add_trailing_slash" .Values.ingress.path }}api/upload/resumable_upload {
                # Disable request and response buffering
                proxy_request_buffering  off;
                proxy_buffering          off;
                proxy_http_version       1.1;
                # Add X-Forwarded-* headers
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header         Upgrade $http_upgrade;
                proxy_set_header         Connection "upgrade";
                client_max_body_size     0;
                proxy_pass http://{{ template "galaxy.fullname" . }}-tusd:1080/files;
            }
{{ end }}
        # end server
        }
    # end http
    }
