---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-cvmfs-fix
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
data:
  cvmfs-fix.sh: |
    sleep 10;
    status=`kubectl get pods -n {{ .Release.Namespace }} -l 'app=cvmfscsi' -l 'component=nodeplugin' -o custom-columns=STATUS:.status.phase --no-headers | sort | uniq | tr -d '\n'`
    while [ "$status" != "Running" ]; do
      echo "Waiting on nodeplugin pod to enter 'Running' status. Currently '$status'.";
      sleep 1;
      status=`kubectl get pods -n {{ .Release.Namespace }} -l 'app=cvmfscsi' -l 'component=nodeplugin' -o custom-columns=STATUS:.status.phase --no-headers | sort | uniq | tr -d '\n'`
    done && \
    echo "Deleting nodeplugin pods..."
    kubectl get pods -n {{ .Release.Namespace }} -l 'app=cvmfscsi' -l 'component=nodeplugin' -o name | xargs kubectl -n {{ .Release.Namespace }} delete && \
    echo "Deleted nodeplugin pods."
