{{- if .Values.influxdb.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-galaxy-metrics
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # every minute
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: galaxy-metrics-scraper
            image: cloudve/galaxy-metrics-scraper:latest
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: PGHOST
                value: {{ include "galaxy-postgresql.fullname" . }}
              - name: PGDATABASE
                value: galaxy
              - name: PGUSER
                value: {{ .Values.postgresql.galaxyDatabaseUser }}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-galaxy-secrets"
                    key: galaxy-db-password
              - name: INFLUX_URL
                value: "{{ .Values.influxdb.url }}"
              - name: INFLUX_DB
                value: "{{ .Values.influxdb.database }}"
              - name: INFLUX_USER
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-galaxy-secrets"
                    key: influxdb-user
              - name: INFLUX_PASS
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-galaxy-secrets"
                    key: influxdb-password
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  concurrencyPolicy: Forbid
{{- end }}
