{{ if and .Values.galaxy_admin_email (and .Values.galaxy_admin_password .Values.galaxy_api_key) }}
apiVersion: v1
kind: Secret
metadata:
  name: galaxy-admin-secret 
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  password: {{ b64enc .Values.galaxy_admin_password }}
  api-key: {{ b64enc .Values.galaxy_api_key }}
  database_password: {{ b64enc .Values.postgresql.postgresPassword }}
{{ end }}
