{{- if .Values.gateway.enabled -}}
{{- $fullName := include "galaxy.fullname" . -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $fullName }}-gateway
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      {{- if .Values.gateway.hostname }}
      hostname: {{ .Values.gateway.hostname | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      protocol: HTTPS
      port: 443
      {{- if .Values.gateway.hostname }}
      hostname: {{ .Values.gateway.hostname | quote }}
      {{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tls.certificateRef }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
