{{- if and .Values.refdata.enabled (eq .Values.refdata.type "cvmfs") }}
---
# Include the code you want to run when both conditions are met
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-cvmfs-fix-job"
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Release.Name }}-post-install-cvmfs-fix-job"
      labels:
        {{- include "galaxy.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "galaxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      restartPolicy: Never
      containers:
      - name: post-install-kubectl
        image: bitnami/kubectl
        command:
          - "sh"
          - "/script/cvmfs-fix.sh"
        volumeMounts:
            - name: kubectl-script
              mountPath: "/script"
      volumes:
      - name: kubectl-script
        configMap:
          name: "{{ .Release.Name }}-configmap-cvmfs-fix"
{{- end }}

