{{- if and .Values.gateway.enabled .Values.ingress.canary.enabled -}}
{{- $fullName := include "galaxy.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $servicePort := .Values.service.port -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-activity-canary
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
  {{- with .Values.gateway.httpRouteAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.existingGateway | default (printf "%s-gateway" $fullName) }}
      {{- if .Values.gateway.existingGatewayNamespace }}
      namespace: {{ .Values.gateway.existingGatewayNamespace }}
      {{- else }}
      namespace: {{ .Release.Namespace }}
      {{- end }}
  {{- if .Values.gateway.hostname }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ trimSuffix "/" $ingressPath }}/api/users
      backendRefs:
        - name: {{ $fullName }}-nginx
          port: {{ $servicePort }}
{{- end }}
