# This canary ingress is used for cloudman autoscaling support
# on activity. A 200 on this endpoint indicates that a user
# is active on the system, and the cluster can be autoscaled
# in anticipation of jobs
---
{{- if .Values.ingress.canary.enabled -}}
{{- $fullName := include "galaxy.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $servicePort := .Values.service.port -}}
{{- $k8s_version := .Capabilities.KubeVersion.Version | toString }}
{{- if semverCompare "^1.19-0" $k8s_version -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare "^1.14-0" $k8s_version -}}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
{{ fail "This chart requires Kubernetes v1.14 or later" }}
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-activity-canary
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}/api/users/
            pathType: Prefix
            backend:
{{- if semverCompare "^1.19-0" $k8s_version }}
              service:
                name: {{ $fullName }}-nginx
                port:
                  number: {{ $servicePort }}
{{- else }}
              serviceName: {{ $fullName }}-nginx
              servicePort: {{ $servicePort }}
{{- end }}
    {{- end }}
  {{- end }}
---
