apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: {{ include "galaxy.fullname" . }}-job-priority
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
value: -1000
preemptionPolicy: Never
globalDefault: false
description: "Galaxy jobs will run when cluster resources are available and will not preempt existing workloads."
