{{- if and .Values.jobs.priorityClass.enabled (not .Values.jobs.priorityClass.existingClass) }}
{{- $k8s_version := .Capabilities.KubeVersion.Version | toString }}
{{- if semverCompare "^1.17.0-0" $k8s_version }}
apiVersion: scheduling.k8s.io/v1
{{- else if semverCompare "^1.14.0-0" $k8s_version }}
apiVersion: scheduling.k8s.io/v1beta1
{{ else }}
  {{ fail "This chart requires Kubernetes v1.14 or later"}}
{{- end }}
kind: PriorityClass
metadata:
  name: {{ include "galaxy.pod-priority-class" . }}
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
value: -1000
preemptionPolicy: Never
globalDefault: false
description: "Galaxy jobs will run when cluster resources are available and will not preempt existing workloads."
{{ end }}
