{{ if and .Values.jobHandlers.priorityClass.enabled (not .Values.jobHandlers.priorityClass.existingClass) }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "galaxy.pod-priority-class" . }}
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
value: -1000
preemptionPolicy: Never
globalDefault: false
description: "Galaxy jobs will run when cluster resources are available and will not preempt existing workloads."
{{ end }}
