{{- if .Values.cvmfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "galaxy.fullname" . }}-cvmfs-gxy-main-pvc
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.cvmfs.main.pvc.storage }}
  storageClassName: {{ .Values.cvmfs.main.pvc.storageClassName }}
{{- end }}
