{{- if .Values.cvmfs.enabled }}
{{- range $key, $entry := .Values.cvmfs.galaxyPersistentVolumeClaims -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "galaxy.fullname" $ }}-cvmfs-gxy-{{ $key }}-pvc
  labels:
    {{- include "galaxy.labels" $ | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ $entry.storage }}
{{- if eq $.Values.refdata.type "s3csi" }}
  volumeName: {{ include "galaxy.fullname" $ }}-refdata-gxy-pv
{{- end }}
  storageClassName: {{ $entry.storageClassName }}
---
{{- end }}
{{- end }}
