{{ if .Values.rbac.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "galaxy.fullname" . }}-role-pod-jobs
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "galaxy.fullname" . }}-batch-ops
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "galaxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "galaxy.fullname" . }}-role-pod-jobs
  apiGroup: rbac.authorization.k8s.io
{{ end }}
