{{ if .Values.rbac.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "galaxy.fullname" . }}-role-pod-jobs
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "galaxy.fullname" . }}-batch-ops
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "galaxy.fullname" . }}-role-pod-jobs
  apiGroup: rbac.authorization.k8s.io
{{ end }}
