apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-galaxy-secrets
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # xref: https://github.com/helm/helm/issues/3053
    # xref: https://github.com/helm/helm/pull/5290
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  galaxy-config-id-secret: {{ (index .Values "configs" "galaxy.yml" "galaxy" "id_secret" | default (randAlphaNum 32)) | b64enc | quote }}
{{- if .Values.influxdb.enabled }}
  influxdb-user: {{ default "galaxy" .Values.influxdb.username | b64enc | quote }}
  influxdb-password: {{  default (randAlphaNum 16) .Values.influxdb.password | b64enc | quote }}
{{- end -}}
{{- if not .Values.postgresql.galaxyExistingSecret }}
  {{ default "galaxy-db-password" .Values.postgresql.galaxyExistingSecretKeyRef }}: {{ include "galaxy.galaxyDbPassword" . | b64enc | quote }}
{{- end }}

