{{ if .Values.postgresql.initdbScriptsSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-galaxy-initdb
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
stringData:
  {{- $root := . }}
  {{ range $path, $bytes := .Files.Glob "files/conf.d/*" }}
    {{- base $path }}: {{ tpl ($root.Files.Get $path) $ | quote }}
  {{ end }}
{{ end }}
