{{ if .Values.tusd.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "galaxy.fullname" . }}-tusd
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 1080
    targetPort: tusd-http
    protocol: TCP
    name: tusd
  selector:
    app.kubernetes.io/component: galaxy-tusd-handler
    {{- include "galaxy.selectorLabels" . | nindent 4 }}
{{- end }}
