---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "galaxy.fullname" . }}-galaxy
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: galaxy-http
    protocol: TCP
    name: gunicorn
  selector:
    app.kubernetes.io/component: galaxy-web-handler
    {{- include "galaxy.selectorLabels" . | nindent 4 }}
