apiVersion: v1
kind: Service
metadata:
  name: {{ include "galaxy.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: galaxy-nginx
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "galaxy.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: galaxy-nginx
