{
 "title": "Galaxy Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Currently Running and Queued Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job_queue",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    },
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "Workflow Invocations Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "Currently Running Tools",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": "Total Galaxy Histories",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 28 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-histories",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Workflow Invocations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 28 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-jobs",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}