{
 "title": "Galaxy Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Currently Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-jobs",
     "query": "SELECT \"count\" FROM \"server-jobs\" WHERE (\"state\" = 'running') AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": "Workflow Invocations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-jobs",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Currently Running and Queued Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "job_queue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    },
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "Workflow Invocations Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Currently Running Tools",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Histories",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-histories",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Datasets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-datasets",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}