apiVersion: v2
name: galaxy
type: application
version: 5.4.0-anvil.3
appVersion: "22.05"
description: Chart for Galaxy, an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
  - name: postgresql
    repository: https://charts.helm.sh/stable/
    version: 8.1.4
    condition: postgresql.deploy
    alias: postgresql
    tags:
      - deploy-postgres
  - name: csi-s3
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 0.31.3
    condition: s3csi.deploy
    alias: s3csi
    tags:
      - deploy-s3csi
  - name: galaxy-cvmfs-csi
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 2.0.0
    condition: cvmfs.deploy
    alias: cvmfs
    tags:
      - deploy-cvmfs
  - name: rabbitmq-cluster-operator
    repository: https://charts.bitnami.com/bitnami
    version: 2.6.12
    condition: rabbitmq.deploy
    alias: rabbitmq
    tags:
      - deploy-rabbitmq
