apiVersion: v2
name: galaxy
type: application
version: 5.0.0
appVersion: "21.09"
description: Chart for Galaxy, an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
  - name: postgres-operator
    repository: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator/
    version: 1.7.0
    condition: postgresql.deploy
    alias: postgresql
    tags:
      - deploy-postgres
  - name: csi-s3
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 0.31.3
    condition: s3csi.deploy
    alias: s3csi
    tags:
      - deploy-s3csi
