apiVersion: v2
name: galaxy
type: application
version: 4.1.0
appVersion: "21.01"
description: Chart for Galaxy, an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
    - name: postgresql
      repository: https://charts.helm.sh/stable/
      version: 8.1.4
      condition: postgresql.enabled
    - name: galaxy-cvmfs-csi
      repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
      version: 1.3.2
      condition: cvmfs.deploy
      alias: cvmfs
