apiVersion: v2
name: galaxy
type: application
version: 4.4.1
appVersion: "21.05"
description: Chart for Galaxy, an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
    - name: postgres-operator
      repository: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator/
      version: 1.6.3
      alias: postgresql
      condition: postgresql.deploy
    - name: galaxy-cvmfs-csi
      repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
      version: 1.6.0
      condition: cvmfs.deploy
      alias: cvmfs
