apiVersion: v2
name: galaxy
type: application
version: 4.0.0-rc.1
appVersion: "21.01"
description: Chart for Galaxy, an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
    - name: postgresql
      repository: "https://raw.githubusercontent.com/zalando/postgres-operator/v1.6.1/charts/postgres-operator/"
      version: 1.6.1
      condition: postgresql.deploy
    - name: galaxy-cvmfs-csi
      repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
      version: 1.3.2
      condition: cvmfs.deploy
      alias: cvmfs
