apiVersion: v2
name: galaxy
type: application
version: 6.1.1
appVersion: "25.0.rc1"
description: Chart for Galaxy, an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png

# This helm chart has no direct dependencies. However, it expects external environmental
# dependencies, such as cluster-wide operators for postgres, rabbitmq and cvmfs for example, to be preinstalled.
# This can be done more conveniently by installing the galaxy-deps chart.
dependencies: []
