dependencies:
    - name: postgresql
      repository: https://charts.helm.sh/stable/
      version: 8.1.4
      condition: postgresql.enabled
    - name: galaxy-cvmfs-csi
      repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
      version: 1.6.0
      condition: cvmfs.deploy
      alias: cvmfs
    - name: csi-s3
      repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
      version: 0.31.3
      condition: s3csi.deploy
      alias: s3csi
      tags:
        - deploy-s3csi
