## Here, helm keeps track of the dependencies that are required for the
## application. Dependencies should be listed here, then the dependencies
## updated with:
##
##    helm dep update
##
## and the requirements.lock file committed.
dependencies:
    - name: postgresql
      repository: https://charts.helm.sh/stable/
      version: 8.1.4
      condition: postgresql.enabled
    - name: galaxy-cvmfs-csi
      repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
      version: 1.3.2
      condition: cvmfs.deploy
      alias: cvmfs
