dependencies:
    - name: postgresql
      repository: https://charts.helm.sh/stable/
      version: 8.1.4
      condition: postgresql.enabled
    - name: galaxy-cvmfs-csi
      repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
      version: 1.3.2
      condition: cvmfs.deploy
      alias: cvmfs
