{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingDatabase) }}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
    team: galaxy
  name: {{ include "galaxy-postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  allowedSourceRanges: []
  databases:
    galaxy: {{ .Values.postgresql.galaxyDatabaseUser }}
  numberOfInstances: 1
  teamId: {{ include "galaxy-postgresql.teamId" . }}
  users:
    {{ .Values.postgresql.galaxyDatabaseUser }}: [ ]
  postgresql:
    version: '13'
  volume:
    size: {{ default "10Gi" .Values.postgresql.persistence.size }}
    {{- if .Values.postgresql.persistence.storageClass }}
    storageClass: {{ .Values.postgresql.persistence.storageClass }}
    {{- end }}
  {{- if and .Values.postgresql.persistence .Values.postgresql.persistence.extra -}}
  {{- tpl (toYaml .Values.postgresql.persistence.extra) . | nindent 4 }}
  {{- end }}
  {{- if and .Values.postgresql.operator .Values.postgresql.operator.operatorSpecExtra -}}
  {{- tpl (toYaml .Values.postgresql.operator.operatorSpecExtra) . | nindent 2 }}
  {{- end }}
{{- end }}
