{{- if not (or .Values.postgresql.enabled .Values.postgresql.existingDatabase) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgresql.galaxyDatabaseUser }}.{{ include "galaxy-postgresql.fullname" . }}.credentials.postgresql.acid.zalan.do
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgresql.galaxyDatabaseUser | b64enc | quote }}
  password: {{ include "galaxy.galaxyDbPassword" . | b64enc | quote }}
{{- end }}
