{{- if not (or .Values.postgresql.enabled .Values.postgresql.existingDatabase) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres.{{ include "galaxy-postgresql.fullname" . }}.credentials.postgresql.acid.zalan.do
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  username: {{ printf "postgres" | b64enc | quote }}
  password: {{ default (randAlphaNum 32) .Values.postgresql.postgresqlPostgresPassword | b64enc | quote }}
{{- end }}
