{{- if not (and .Values.postgresql.enabled .Values.postgresql.existingDatabase) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "galaxy-postgresql.fullname" . }}-primaryuser-secret
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  username: {{ printf "primaryuser" | b64enc | quote }}
  password: {{ default (randAlphaNum 32) .Values.postgresql.operator.primaryUserPassword | b64enc | quote }}
{{- end }}
