{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingDatabase) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: postgres.{{ include "galaxy-postgresql.fullname" . }}.credentials.postgresql.cnpg.io
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
data:
  username: {{ printf "postgres" | b64enc | quote }}
  password: {{ default (randAlphaNum 32) .Values.postgresql.postgresqlPostgresPassword | b64enc | quote }}
{{- end }}
