{{- if not (and .Values.postgresql.enabled .Values.postgresql.existingDatabase) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "galaxy-postgresql.fullname" . }}-{{ .Values.postgresql.galaxyDatabaseUser }}-secret
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  username: {{ .Values.postgresql.galaxyDatabaseUser | b64enc | quote }}
  password: {{ include "galaxy.galaxyDbPassword" . | b64enc | quote }}
{{- end }}
