apiVersion: v2
name: galaxy-deps
type: application
version: 1.0.0
appVersion: "23.1"
description: Chart containing environmental dependencies needed by Galaxy. Galaxy is an open, web-based platform for accessible, reproducible, and transparent computational biomedical research.
icon: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
dependencies:
  - name: postgres-operator
    repository: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator/
    version: 1.9.0
    condition: postgresql.deploy
    alias: postgresql
    tags:
      - deploy-postgres
  - name: csi-s3
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 0.35.2
    condition: s3csi.deploy
    alias: s3csi
    tags:
      - deploy-s3csi
  - name: galaxy-cvmfs-csi
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 2.2.0
    condition: cvmfs.deploy
    alias: cvmfs
    tags:
      - deploy-cvmfs
  - name: rabbitmq-cluster-operator
    repository: https://charts.bitnami.com/bitnami
    version: 2.6.12
    condition: rabbitmq.deploy
    alias: rabbitmq
    tags:
      - deploy-rabbitmq
