apiVersion: v1
kind: ReplicationController
metadata:
        name: postgresql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
         app: postgresql-server
    spec:
      containers:
      - name: postgresql-server
        image: {{.Values.postgres_image}}{{.Values.postgres_image_tag}}
        env:
          - name: "PGDATA"
            value: {{.Values.postgres_mount_point_PGDATA}}/{{.Values.postgres_PGDATA}}
          - name: "POSTGRES_DB"
            value: {{ .Values.postgresql.postgresDatabase }}
          - name: "POSTGRES_USER"
            value: {{ .Values.postgresql.postgresUser }}
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                      name: galaxy-postgres-secret
                      key: password 
        ports:
          - containerPort: 5432
{{ if .Values.postgres_pvc }}
        volumeMounts:
          - mountPath: {{.Values.postgres_mount_point_PGDATA}}
            name: postgres-pvc
{{ if .Values.subpath }}
            subPath: {{.Values.subpath}}
{{ end }}
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
              claimName: {{.Values.postgres_pvc}}
{{ end }}
